### ISSUE TITLE
I have a error with carpet 1.12.2 

### ISSUE THREAD

**Issue by SwadowMaster** [gnembon/carpetmod112#134]
I execute carpet 1.12.2 on my PC and send this crash report:
```--- Minecraft Crash Report ----
// Why did you do that?
Time: 9/12/20 14:24
Description: Exception in server tick loop
java.util.ConcurrentModificationException
    at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:742)
    at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:558)
    at carpet.pubsub.PubSubManager.getOrCreateNode(PubSubManager.java:38)
    at carpet.pubsub.PubSubInfoProvider.<init>(PubSubInfoProvider.java:18)
    at carpet.CarpetServer.onLoadAllWorlds(CarpetServer.java:81)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:324)
    at nz.j(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:539)
    at java.base/java.lang.Thread.run(Thread.java:832)
A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------
-- System Details --
Details:
    Minecraft Version: 1.12.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 15, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
    Memory: 64978784 bytes (61 MB) / 176160768 bytes (168 MB) up to 4278190080 bytes (4080 MB)
    JVM Flags: 0 total;
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Profiler Position: N/A (disabled)     Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'carpetmod'
    Type: Dedicated Server (map_server.txt)
```

How can i do to solve it?

**Comment by Earthcomputer** [comment]
Try running with Java 8 rather than Java 15

**Comment by SwadowMaster** [comment]
this is the java i have installed 
![image](https://user-images.githubusercontent.com/72133740/101980487-026d9980-3c66-11eb-8438-a197ab3ff3c3.png)

**Comment by SwadowMaster** [comment]
the same error 
![image](https://user-images.githubusercontent.com/72133740/101980627-0948dc00-3c67-11eb-9c4a-a30e9e7b3f32.png)

**Comment by skyrising** [comment]
I guess we need to backport https://github.com/DeadlyMC/QuickCarpet114/commit/9599f60

**Comment by SwadowMaster** [comment]
-I have to modify the code then?

**Comment by SwadowMaster** [comment]
I use this carpet https://github.com/gnembon/carpetmod112/releases and I can't find that file

**Comment by Earthcomputer** [comment]
Fixed in v20_12_12, thanks sky!

**Comment by SwadowMaster** [comment]
I tried with this   https://github.com/gnembon/carpetmod112
 but it doesn't work for me I get the error from before

**Comment by skyrising** [comment]
Did you use the new ([20_12_12](https://github.com/gnembon/carpetmod112/releases/tag/v20_12_12)) version? Not quite clear since you linked to the repository, not something specific.

**Comment by SwadowMaster** [comment]
yes

**Comment by SwadowMaster** [comment]
Can you pass me a carpet that works for localhost pls
