### ISSUE TITLE
NPE whilst logging damage and player attacked by a mob with enchanted weapon

### ISSUE THREAD

**Issue by gnembon** [gnembon/carpetmod112#14]

**Comment by gnembon** [comment]
reported by TheBlueKingLP

```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2018/7/31 下午7:44
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at carpet.logging.logHelpers.DamageReporter.modify_damage(DamageReporter.java:77)
	at adc.B(EntityMob.java:117)
	at adr.B(SourceFile:263)
	at xm.a(SourceFile:127)
	at xm.e(SourceFile:119)
	at yo.e(SourceFile:28)
	at xd.a(SourceFile:129)
	at vo.cA(EntityLiving.java:822)
	at vn.n(EntityLivingBase.java:2487)
	at vo.n(EntityLiving.java:638)
	at adc.n(EntityMob.java:54)
	at adr.n(SourceFile:213)
	at vn.B_(EntityLivingBase.java:2303)
	at vo.B_(EntityLiving.java:337)
	at adc.B_(EntityMob.java:62)
	at ve.aE(Entity.java:2168)
	at vn.aE(EntityLivingBase.java:2631)
	at ams.a(World.java:1905)
	at om.a(WorldServer.java:895)
	at ams.h(World.java:1873)
	at ams.a(World.java:1970)
	at om.a(WorldServer.java:895)
	at ams.h(World.java:1873)
	at ams.k(World.java:1690)
	at om.k(WorldServer.java:670)
	at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:820)
	at nx.D(DedicatedServer.java:406)
	at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:582)
	at java.base/java.lang.Thread.run(Thread.java:844)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at carpet.logging.logHelpers.DamageReporter.modify_damage(DamageReporter.java:77)
	at adc.B(EntityMob.java:117)
	at adr.B(SourceFile:263)
	at xm.a(SourceFile:127)
	at xm.e(SourceFile:119)
	at yo.e(SourceFile:28)
	at xd.a(SourceFile:129)
	at vo.cA(EntityLiving.java:822)
	at vn.n(EntityLivingBase.java:2487)
	at vo.n(EntityLiving.java:638)
	at adc.n(EntityMob.java:54)
	at adr.n(SourceFile:213)
	at vn.B_(EntityLivingBase.java:2303)
	at vo.B_(EntityLiving.java:337)
	at adc.B_(EntityMob.java:62)
	at ve.aE(Entity.java:2168)
	at vn.aE(EntityLivingBase.java:2631)
	at ams.a(World.java:1905)
	at om.a(WorldServer.java:895)
	at ams.h(World.java:1873)
	at ams.a(World.java:1970)
	at om.a(WorldServer.java:895)
	at ams.h(World.java:1873)

-- Entity being ticked --
Details:
	Entity Type: minecraft:boat (afb)
	Entity ID: 19435540
	Entity Name: Boat
	Entity's Exact location: 102.69, 111.00, -150.69
	Entity's Block location: World: (102,111,-151), Chunk: (at 6,6,9 in 6,-10; contains blocks 96,0,-160 to 111,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [add['Zombie Pigman'/20911874, l='world', x=102.65, y=110.45, z=-150.49], add['Zombie Pigman'/20916935, l='world', x=102.81, y=110.45, z=-151.27]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at ams.k(World.java:1690)
	at om.k(WorldServer.java:670)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [oo['<Player Name>'/18519261, l='world', x=116.95, y=58.73, z=-135.03], oo['<Player Name>'/18580962, l='world', x=102.34, y=110.00, z=-149.33]]
	Chunk stats: ServerChunkCache: 513 Drop: 0
	Level seed: -9219846015867837424
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:820)
	at nx.D(DedicatedServer.java:406)
	at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:582)
	at java.base/java.lang.Thread.run(Thread.java:844)

-- System Details --
<I don't want to give these details to anyone>
```
