### ISSUE TITLE
Server instantly crashes while starting if instantScheduling is set to false in carpet.conf

### ISSUE THREAD

**Issue by PentaSteve** [gnembon/carpetmod112#147]
I was messing around with instant scheduling on a creative carpet server, and for some reason I decided to set it to false permanently. Next time the server restarted, in was in an infinite and very rapid crash loop. The only way to fix this was editing carpet.conf

**Comment by Earthcomputer** [comment]
Crash report would be helpful.

**Comment by PentaSteve** [comment]
Yeah, for some reason I didn't even think to provide a crash report.
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2/2/21 4:38 PM
Description: Exception in server tick loop

java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at carpet.CarpetSettings.set(CarpetSettings.java:1235)
	at carpet.CarpetSettings.applySettingsFromConf(CarpetSettings.java:1328)
	at carpet.CarpetServer.onServerLoaded(CarpetServer.java:57)
	at nz.j(DedicatedServer.java:267)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at carpet.CarpetSettings.set(CarpetSettings.java:1232)
	... 5 more
Caused by: java.lang.NullPointerException
	at carpet.CarpetSettings.validateInstantScheduling(CarpetSettings.java:178)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.89-1-MANJARO
	Java Version: 1.8.0_275, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 976448840 bytes (931 MB) / 1053818880 bytes (1005 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xms1G -Xmx4G -Xss1M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Profiler Position: N/A (disabled)
	Player Count: 0 / 69420; []
	Is Modded: Definitely; Server brand changed to 'carpetmod'
	Type: Dedicated Server (map_server.txt)
```

**Comment by CheaterCodes** [comment]
Just had this happen as well, same crash report.
Removing the default setting from carpet.conf fixed the issue.

Carpet_21_01_06b
