### ISSUE TITLE
Crash when player joins server

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/carpetmod112#160]
I have created a carpet server.jar (using masa's instructions [here](https://discord.com/channels/211786369951989762/573613501164159016/573698065383292929) which have worked for me in the past).
It starts up fine, but then when I join it crashes. Here is the crash log:
```
[11:19:44] [Server thread/INFO]: Starting minecraft server version 1.12.2
[11:19:44] [Server thread/INFO]: Loading properties
[11:19:44] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:271) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:282) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:178) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:329) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:396) ~[?:?]
	at nz$2.run(DedicatedServer.java:105) [carpet_server.jar:?]
[11:19:44] [Server thread/INFO]: Default game type: CREATIVE
[11:19:44] [Server thread/INFO]: Generating keypair
[11:19:44] [Server thread/INFO]: Starting Minecraft server on *:25565
[11:19:44] [Server thread/INFO]: Using default channel type
[11:19:45] [Server thread/INFO]: Preparing level "world"
[11:19:46] [Server thread/INFO]: Loaded 488 advancements
[11:19:46] [Server thread/INFO]: Preparing start region for level 0
[11:19:47] [Server thread/INFO]: Preparing spawn area: 0%
[11:19:48] [Server thread/INFO]: Preparing spawn area: 13%
[11:19:49] [Server thread/INFO]: Preparing spawn area: 71%
[11:19:49] [Server thread/INFO]: Done (4.853s)! For help, type "help" or "?"
[11:20:09] [User Authenticator #1/INFO]: UUID of player Ghoulboy is dd736e6b-438f-423f-9392-f8542d53cda9
[11:20:09] [Server thread/INFO]: Ghoulboy[/127.0.0.1:58729] logged in with entity id 301 at (0.0, 0.0, 0.0)
[11:20:09] [Server thread/INFO]: Ghoulboy joined the game
[11:20:11] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.util.HashMap java.util.HashSet.map accessible: module java.base does not "opens java.util" to unnamed module @50c87b21
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at h.a(Util.java:23) [carpet_server.jar:?]
	at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:825) [carpet_server.jar:?]
	at nz.D(DedicatedServer.java:410) [carpet_server.jar:?]
	at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:746) [carpet_server.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602) [carpet_server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.util.HashMap java.util.HashSet.map accessible: module java.base does not "opens java.util" to unnamed module @50c87b21
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
	at carpet.utils.UnloadOrder.getCurrentHashSize(UnloadOrder.java:107) ~[carpet_server.jar:?]
	at carpet.CarpetServer.lambda$onLoadAllWorlds$0(CarpetServer.java:82) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubInfoProvider.get(PubSubInfoProvider.java:65) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubNode.onSubscribe(PubSubNode.java:84) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubNode.subscribe(PubSubNode.java:73) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubManager.subscribe(PubSubManager.java:60) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubMessenger.subscribe(PubSubMessenger.java:70) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubMessenger.onCustomPayload(PubSubMessenger.java:155) ~[carpet_server.jar:?]
	at carpet.network.PluginChannelManager.process(PluginChannelManager.java:69) ~[carpet_server.jar:?]
	at pa.a(NetHandlerPlayServer.java:1929) ~[carpet_server.jar:?]
	at lh.a(SourceFile:58) ~[carpet_server.jar:?]
	at lh.a(SourceFile:8) ~[carpet_server.jar:?]
	at hv$1.run(SourceFile:13) ~[carpet_server.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at h.a(Util.java:22) ~[carpet_server.jar:?]
	... 5 more
[11:20:13] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.util.HashMap java.util.HashSet.map accessible: module java.base does not "opens java.util" to unnamed module @50c87b21
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
	at carpet.utils.UnloadOrder.getCurrentHashSize(UnloadOrder.java:107) ~[carpet_server.jar:?]
	at carpet.CarpetServer.lambda$onLoadAllWorlds$0(CarpetServer.java:82) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubInfoProvider.get(PubSubInfoProvider.java:65) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubNode.update(PubSubNode.java:145) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubNode.update(PubSubNode.java:148) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubNode.update(PubSubNode.java:148) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubNode.update(PubSubNode.java:148) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubNode.update(PubSubNode.java:148) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubNode.update(PubSubNode.java:148) ~[carpet_server.jar:?]
	at carpet.pubsub.PubSubManager.update(PubSubManager.java:72) ~[carpet_server.jar:?]
	at carpet.CarpetServer.tick(CarpetServer.java:119) ~[carpet_server.jar:?]
	at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:732) ~[carpet_server.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602) [carpet_server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[11:20:13] [Server thread/ERROR]: This crash report has been saved to: C:\myfilepath\.\crash-reports\crash-2021-08-20_11.20.13-server.txt
[11:20:13] [Server thread/INFO]: Stopping server
[11:20:13] [Server thread/INFO]: Saving players
[11:20:13] [Server thread/INFO]: Saving worlds
[11:20:13] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[11:20:14] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[11:20:14] [Server thread/INFO]: Saving chunks for level 'world'/the_end
[11:20:15] [Server Shutdown Thread/INFO]: Stopping server
[11:20:15] [Server Shutdown Thread/INFO]: Saving players
```

On my client, I see myself join, and then just before I can begin to move my player about it crashes and kicks me out.
I also tried this on older versions, and it is still an issue, so idk if it's a bug with carpet or a problem with what I'm doing tbh.

**Comment by skyrising** [comment]
You're probably using Java 16 and running into the JDK's increased encapsulation. Add `--add-opens java.base/java.util=ALL-UNNAMED` to your JVM arguments to fix.

**Comment by Ghoulboy78** [comment]
Unfortunately the problem persists even with this JVM argument added

**Comment by Ghoulboy78** [comment]
Turns out I had to just use java 12 to get it to work.
