### ISSUE TITLE
Can't build v19_08_11

### ISSUE THREAD

**Issue by Cnastret** [gnembon/carpetmod112#186]
I know this version is old but I don't think it is a issue with the program. I am just doing it wrong. I think I need this version because it doesn't seem to be for 1.12.2, but for 1.12.0. I try to run ./gradlew setupCarpetmod in the terminal but it doesn't work because I am not using java 1.8. I don't know how. I have it installed but I can seem to figure out how to use it instead of java 17 or 21. 

$ ./gradlew setupCarpetmod
```

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

I tried to build it with intellij idea. I changed the java version to 1.8 but it said:
```

A problem occurred configuring root project 'carpetmod'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve gradle.plugin.com.dorongold.plugins:task-tree:1.3.
     Required by:
         project :
      > Could not resolve gradle.plugin.com.dorongold.plugins:task-tree:1.3.
         > Could not get resource 'http://plugins.gradle.org/m2/gradle/plugin/com/dorongold/plugins/task-tree/1.3/task-tree-1.3.pom'.
            > Could not GET 'http://plugins.gradle.org/m2/gradle/plugin/com/dorongold/plugins/task-tree/1.3/task-tree-1.3.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

**Comment by Cnastret** [comment]
I tried to instead manually splice the server.jar and the v19_08_11 patches. Now I am able to generate what I think are all of the files, but only by using this command:
`java -Xmx1024M -Xms1024M -jar server.jar nogui`
 I am not able to just double click the jar file. I have tried with both oracle and adoptium. 
The server.properties file and the eula.txt are generated with these messages:
```
[21:50:38] [main/ERROR]: Errors with built-in recipes!
[21:50:38] [Server thread/INFO]: Starting minecraft server version 1.12
[21:50:38] [Server thread/INFO]: Loading properties
[21:50:38] [Server thread/WARN]: server.properties does not exist
[21:50:38] [Server thread/INFO]: Generating new properties file
[21:50:38] [Server thread/WARN]: Failed to load eula.txt
[21:50:38] [Server thread/INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.
[21:50:38] [Server thread/INFO]: Stopping server
[21:50:38] [Server Shutdown Thread/INFO]: Stopping server
```
Then I run the jar again and the rest is generated but the server doesn't start running:
```
[21:51:54] [main/ERROR]: Errors with built-in recipes!
[21:51:54] [Server thread/INFO]: Starting minecraft server version 1.12
[21:51:54] [Server thread/INFO]: Loading properties
[21:51:54] [Server thread/INFO]: Default game type: SURVIVAL
[21:51:54] [Server thread/INFO]: Generating keypair
[21:51:54] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:51:54] [Server thread/INFO]: Using default channel type
[21:51:54] [Server thread/INFO]: Preparing level "world"
[21:51:54] [Thread-2/INFO]: [STDERR]: java.io.FileNotFoundException: carpet\joined.srg (The system cannot find the file specified)
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at java.io.FileInputStream.open0(Native Method)
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.lambda$loadMappings$0(StackTraceDeobfuscator.java:168)
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:750)
[21:51:54] [Thread-2/INFO]: [STDERR]: java.lang.NullPointerException: in is null
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:101)
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:80)
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.lambda$loadMappings$0(StackTraceDeobfuscator.java:173)
[21:51:54] [Thread-2/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:750)
[21:51:54] [Server thread/INFO]: Loaded 488 advancements
```
It is missing the joined.srg file. What is that?
Do you know why this is happening?

**Comment by non-bin** [comment]
same problem here, there's not much documentations :(

It seems that [v19_08_11](https://github.com/gnembon/carpetmod112/releases/tag/v19_08_11) was the last to support 1.12.0 but even using the mktest script from it's commit and manually downloading the server.jar.orig I get exactly that output.

Manually merging the jar files (I don't know what I'm doing, I just copied everything from the carpet zip into the server jar, overwriting duplicates) it says this:

```
Exception in thread "main" [15:39:30] [main/INFO]: [STDERR]: java.lang.NoClassDefFoundError: carpet/patches/BlockWool
[15:39:30] [main/INFO]: [STDERR]: 	at aou.w(Block.java:1168)
[15:39:30] [main/INFO]: [STDERR]: 	at ng.c(Bootstrap.java:574)
[15:39:30] [main/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.main(SourceFile:672)
[15:39:30] [main/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: carpet.patches.BlockWool
[15:39:30] [main/INFO]: [STDERR]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
[15:39:30] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[15:39:30] [main/INFO]: [STDERR]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[15:39:30] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[15:39:30] [main/INFO]: [STDERR]: 	... 3 more
```

and for reference this is the output from runnning the `mktest.sh` version:

```
[15:33:47] [main/ERROR]: Errors with built-in recipes!
[15:33:47] [Server thread/INFO]: Starting minecraft server version 1.12
[15:33:47] [Server thread/INFO]: Loading properties
[15:33:47] [Server thread/INFO]: Default game type: SURVIVAL
[15:33:47] [Server thread/INFO]: Generating keypair
[15:33:47] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:33:47] [Server thread/INFO]: Using epoll channel type
[15:33:48] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[15:33:48] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[15:33:48] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[15:33:48] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[15:33:48] [Server thread/INFO]: Preparing level "MinceRaft"
[15:33:48] [Thread-2/INFO]: [STDERR]: java.io.FileNotFoundException: carpet/joined.srg (No such file or directory)
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at java.io.FileInputStream.open0(Native Method)
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.lambda$loadMappings$0(StackTraceDeobfuscator.java:168)
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:750)
Exception in thread "Thread-2" [15:33:48] [Thread-2/INFO]: [STDERR]: java.lang.NullPointerException: in is null
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:101)
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:80)
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.lambda$loadMappings$0(StackTraceDeobfuscator.java:173)
[15:33:48] [Thread-2/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:750)
[15:33:48] [Server thread/INFO]: Loaded 488 advancements
^C[15:38:01] [Server Shutdown Thread/INFO]: Stopping server
2025-10-07 15:38:01,692 Server Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
```

**Comment by non-bin** [comment]
I found the install instructions in the `docs/usage` directory so following it's instructions I cloned the repo (at `v19_08_11`), updated the url in the mktest.sh script to `https://piston-data.mojang.com/v1/objects/8494e844e911ea0d63878f64da9dcc21f53a3463/server.jar`, then ran the following to build and test but it still doesn't work :(

```console
$ ./mktest.sh -d "https://github.com/gnembon/carpetmod112/releases/download/v19_08_11/carpetmod112-19_08_11.zip" -o carpet-server-1_12.jar
Cleaning previous installations ...
Downloading patches...
--2025-11-02 15:30:09--  https://github.com/gnembon/carpetmod112/releases/download/v19_08_11/carpetmod112-19_08_11.zip
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/140645007/546a6d80-bc74-11e9-9ba3-9f31d9370b71?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-11-02T05%3A22%3A18Z&rscd=attachment%3B+filename%3Dcarpetmod112-19_08_11.zip&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-11-02T04%3A21%3A37Z&ske=2025-11-02T05%3A22%3A18Z&sks=b&skv=2018-11-09&sig=d1YF3zpFt1y%2FZHCtR3Uexe4h6ymInGrwtvd4GVXiC2Q%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2MjA1ODExMCwibmJmIjoxNzYyMDU3ODEwLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.1IFUVutsu_0dOzzwIRXKue6fqEo8-3focY-7zP_zU2Q&response-content-disposition=attachment%3B%20filename%3Dcarpetmod112-19_08_11.zip&response-content-type=application%2Foctet-stream [following]
--2025-11-02 15:30:10--  https://release-assets.githubusercontent.com/github-production-release-asset/140645007/546a6d80-bc74-11e9-9ba3-9f31d9370b71?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-11-02T05%3A22%3A18Z&rscd=attachment%3B+filename%3Dcarpetmod112-19_08_11.zip&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-11-02T04%3A21%3A37Z&ske=2025-11-02T05%3A22%3A18Z&sks=b&skv=2018-11-09&sig=d1YF3zpFt1y%2FZHCtR3Uexe4h6ymInGrwtvd4GVXiC2Q%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2MjA1ODExMCwibmJmIjoxNzYyMDU3ODEwLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.1IFUVutsu_0dOzzwIRXKue6fqEo8-3focY-7zP_zU2Q&response-content-disposition=attachment%3B%20filename%3Dcarpetmod112-19_08_11.zip&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1466927 (1.4M) [application/octet-stream]
Saving to: ‘/home/alice/repos/carpetmod112/download/carpet_patches.zip’

/home/alice/repos/carpetmod112 100%[===================================================>]   1.40M  5.43MB/s    in 0.3s

2025-11-02 15:30:11 (5.43 MB/s) - ‘/home/alice/repos/carpetmod112/download/carpet_patches.zip’ saved [1466927/1466927]

Copying server ...
Downloading server ...
--2025-11-02 15:30:11--  https://piston-data.mojang.com/v1/objects/8494e844e911ea0d63878f64da9dcc21f53a3463/server.jar
Resolving piston-data.mojang.com (piston-data.mojang.com)... 13.107.246.32, 13.107.213.32, 2620:1ec:bdf::32, ...
Connecting to piston-data.mojang.com (piston-data.mojang.com)|13.107.246.32|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30202458 (29M) [application/zip]
Saving to: ‘/home/alice/repos/carpetmod112/build/tmp/fullRelease/minecraft_server.1.12.jar’

/home/alice/repos/carpetmod112 100%[===================================================>]  28.80M  5.63MB/s    in 5.2s

2025-11-02 15:30:16 (5.58 MB/s) - ‘/home/alice/repos/carpetmod112/build/tmp/fullRelease/minecraft_server.1.12.jar’ saved [30202458/30202458]

Extracting patches ...
Patch work ...
~/repos/carpetmod112/build/tmp/fullRelease/patches ~/repos/carpetmod112
~/repos/carpetmod112
Cleanup ...
~/repos/carpetmod112/build/tmp/fullRelease ~/repos/carpetmod112
~/repos/carpetmod112
$ mkdir tmp
$ mv carpet-server-1_12.jar tmp
$ cd tmp
$ echo "eula=true" > eula.txt
$ java -jar carpet-server-1_12.jar nogui
[15:30:54] [main/ERROR]: Errors with built-in recipes!
[15:30:54] [Server thread/INFO]: Starting minecraft server version 1.12
[15:30:54] [Server thread/INFO]: Loading properties
[15:30:54] [Server thread/INFO]: Default game type: SURVIVAL
[15:30:54] [Server thread/INFO]: Generating keypair
[15:30:54] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:30:54] [Server thread/INFO]: Using epoll channel type
[15:30:54] [Server thread/INFO]: Preparing level "world"
[15:30:54] [Thread-1/INFO]: [STDERR]: java.io.FileNotFoundException: carpet/joined.srg (No such file or directory)
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at java.base/java.io.FileInputStream.open(Unknown Source)
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at java.base/java.io.FileInputStream.<init>(Unknown Source)
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.lambda$loadMappings$0(StackTraceDeobfuscator.java:168)
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-1" [15:30:54] [Thread-1/INFO]: [STDERR]: java.lang.NullPointerException: in is null
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at java.base/java.util.zip.ZipInputStream.<init>(Unknown Source)
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at java.base/java.util.zip.ZipInputStream.<init>(Unknown Source)
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at carpet.helpers.StackTraceDeobfuscator.lambda$loadMappings$0(StackTraceDeobfuscator.java:173)
[15:30:54] [Thread-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[15:30:54] [Server thread/INFO]: Loaded 488 advancements
say hi # Does nothing
^C # It hangs here so I have to ctrl+C
[15:31:31] [Server Shutdown Thread/INFO]: Stopping server
[15:31:31] [Server Shutdown Thread/INFO]: Saving players
2025-11-02 15:31:31,697 Server Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
Exception in thread "Server Shutdown Thread"
$ touch carpet/joined.srg
$ java -jar carpet-server-1_12.jar nogui
[15:32:37] [main/ERROR]: Errors with built-in recipes!
[15:32:37] [Server thread/INFO]: Starting minecraft server version 1.12
[15:32:37] [Server thread/INFO]: Loading properties
[15:32:37] [Server thread/INFO]: Default game type: SURVIVAL
[15:32:37] [Server thread/INFO]: Generating keypair
[15:32:37] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:32:37] [Server thread/INFO]: Using epoll channel type
[15:32:37] [Server thread/INFO]: Preparing level "world"
[15:32:38] [Server thread/INFO]: Loaded 488 advancements
say hi # Still nothing
^C # That's one less error but it still hangs
[15:33:45] [Server Shutdown Thread/INFO]: Stopping server
2025-11-02 15:33:45,266 Server Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
Exception in thread "Server Shutdown Thread"
```

**Comment by non-bin** [comment]
If I copy an existing 1.12 world it crashes and I get the following:

```console
$ java -jar carpet-server-1_12.jar nogui
[15:51:51] [main/ERROR]: Errors with built-in recipes!
[15:51:51] [Server thread/INFO]: Starting minecraft server version 1.12
[15:51:51] [Server thread/INFO]: Loading properties
[15:51:51] [Server thread/WARN]: server.properties does not exist
[15:51:51] [Server thread/INFO]: Generating new properties file
[15:51:51] [Server thread/INFO]: Default game type: SURVIVAL
[15:51:51] [Server thread/INFO]: Generating keypair
[15:51:51] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:51:51] [Server thread/INFO]: Using epoll channel type
[15:51:51] [Server thread/INFO]: Preparing level "world"
[15:51:51] [Server thread/INFO]: Loaded 488 advancements
[15:51:51] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.TreeMap.callMappingFunctionWithCheck(Unknown Source) ~[?:?]
	at java.util.TreeMap.computeIfAbsent(Unknown Source) ~[?:?]
	at carpet.pubsub.PubSubManager.getOrCreateNode(PubSubManager.java:38) ~[carpet-server-1_12.jar:?]
	at carpet.pubsub.PubSubInfoProvider.<init>(PubSubInfoProvider.java:18) ~[carpet-server-1_12.jar:?]
	at carpet.CarpetServer.onLoadAllWorlds(CarpetServer.java:81) ~[carpet-server-1_12.jar:?]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:322) ~[carpet-server-1_12.jar:?]
	at nx.j(DedicatedServer.java:267) ~[carpet-server-1_12.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:534) ~[carpet-server-1_12.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[15:51:51] [Server thread/ERROR]: This crash report has been saved to: /home/alice/repos/carpetmod112/tmp/./crash-reports/crash-2025-11-02_15.51.51-server.txt
[15:51:51] [Server thread/INFO]: Stopping server
[15:51:51] [Server thread/INFO]: Saving players
[15:51:51] [Server thread/INFO]: Saving worlds
[15:51:51] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[15:51:51] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[15:51:51] [Server thread/INFO]: Saving chunks for level 'world'/the_end
[15:51:51] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "java.util.Map.isEmpty()" because "waypoints" is null
	at carpet.utils.Waypoint.saveWaypoints(Waypoint.java:184) ~[carpet-server-1_12.jar:?]
	at carpet.CarpetServer.onWorldsSaved(CarpetServer.java:103) ~[carpet-server-1_12.jar:?]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:453) ~[carpet-server-1_12.jar:?]
	at net.minecraft.server.MinecraftServer.u(MinecraftServer.java:487) ~[carpet-server-1_12.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:653) ~[carpet-server-1_12.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[15:51:51] [Server Shutdown Thread/INFO]: Stopping server
[15:51:51] [Server Shutdown Thread/INFO]: Saving players
[15:51:51] [Server Shutdown Thread/INFO]: Saving worlds
$ cat /home/alice/repos/carpetmod112/tmp/./crash-reports/crash-2025-11-02_15.51.51-server.txt
---- Minecraft Crash Report ----
// You're mean.

Time: 2/11/25, 3:51 pm
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap.callMappingFunctionWithCheck(Unknown Source)
	at java.base/java.util.TreeMap.computeIfAbsent(Unknown Source)
	at carpet.pubsub.PubSubManager.getOrCreateNode(PubSubManager.java:38)
	at carpet.pubsub.PubSubInfoProvider.<init>(PubSubInfoProvider.java:18)
	at carpet.CarpetServer.onLoadAllWorlds(CarpetServer.java:81)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:322)
	at nx.j(DedicatedServer.java:267)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:534)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Linux (amd64) version 6.17.6
	Java Version: 21.0.8, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 70647896 bytes (67 MB) / 197132288 bytes (188 MB) up to 4009754624 bytes (3824 MB)
	JVM Flags: 0 total;
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'carpetmod'
	Type: Dedicated Server (map_server.txt)%                     
```

All the same result trying `v19_05_02`

**Comment by non-bin** [comment]
I was running with java 21. With java 8 it doesn't crash in the last case (everything else is the same).
```console
$ touch carpet/joined.srg
$ cp PreGeneratedWorld world
$ java8 -jar carpet-server-1_12.jar nogui
[15:57:54] [main/ERROR]: Errors with built-in recipes!
[15:57:54] [Server thread/INFO]: Starting minecraft server version 1.12
[15:57:54] [Server thread/INFO]: Loading properties
[15:57:54] [Server thread/INFO]: Default game type: SURVIVAL
[15:57:54] [Server thread/INFO]: Generating keypair
[15:57:54] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:57:54] [Server thread/INFO]: Using epoll channel type
[15:57:54] [Server thread/INFO]: Preparing level "world"
[15:57:55] [Server thread/INFO]: Loaded 488 advancements
[15:57:55] [Server thread/INFO]: Preparing start region for level 0
^C
```

It hangs there. If I try to join it says `Invalid session` but if I change `online-mode=false` in `server.properties` I just time out connecting

Sorry for the spam

**Comment by non-bin** [comment]
Trying to build patches manually doesn't work either, all the urls are outdated

**Comment by Earthcomputer** [comment]
You are experiencing issues because you are trying to use a 6 year old version, rather than the latest version. If you think you need 1.12.0, you don't. All differences between 1.12.0 and 1.12.2 are configurable via a carpet rule.

**Comment by non-bin** [comment]
I wanna do falling block palet corruption, I'm still researching but people say the setup only works in 1.12

EDIT: [this](https://www.youtube.com/watch?v=Glg-K2N4g5Q) video from Myren says it works in 1.12.2 so I'll do some testing

**Comment by Earthcomputer** [comment]
Who is "people"? You should ask them *why* the setup only works in 1.12 so that you know which rules to enable.

**Comment by non-bin** [comment]
Ok. It looks like it is possible on 1.12.2, sorry for the unnecessary spam <3
It seems like the build works fine, because when trying the 1.12.2 version, I get the same hang while preparing start region. I get the same issue with [Vastech's version](https://github.com/Void-Skeleton/Carpet-Vastech-Addition), which comes as a prepacked server jar. I would guess it's something to do with my environment (I'm on NixOS which is famosly bad with niche issues). Do you have any debugging tips? verbose logging maybe?

**Comment by TheBjoel2** [comment]
I think I remember it hanging once when it was generating a new world, hanging roughly about the same way. A simple server restart fixed it. Never saw it again. Try doing the same thing. I use arch btw.

**Comment by non-bin** [comment]
Restart doesn't help, it happens every time including when running with a pre generated world

**Comment by TheBjoel2** [comment]
Okaaaay. That's strange.
Speaking about debugging tips. You have intellij, right? That's good, bc intellij can debug things. Open intellij. Close all the active projects if any are open. Then click the "clone the repo or smth like that" button. It will probably ask you to provide a url. intellij then will open this project (not exactly sure, never clicked that button). On the top right corner of your screen, there will be an "elephant" button. Please click that. If the elephant tab has nothing useful inside, wait until intellij *fully* opens your project (it's indexing files or idk). When you see that tasks appeared on the elephant tab, search for a "setupCarpetmod" task. Please run it. After that you can *probably* start debugging. Find the task that runs the server (i forgot how this task is called), but don't just run it. Right click it, and press debug. Then wait until it hangs. After it has hanged, on the left bottom of your screen, locate the "pause button". It should be green. Press it. Now, using the debugging menu, you are able to see what each [thread](https://en.wikipedia.org/wiki/Thread) is doing. Find the thread that hangs. See in which spot of code it hangs. Analyze. Draw conclusions. Report back to here.

**Comment by non-bin** [comment]
Thank you so much! This is brilliant, I don't have intellij but I'll try the trial and report back

**Comment by TheBjoel2** [comment]
what trial?

**Comment by TheBjoel2** [comment]
oooooh, so you're different persons
